[package]
name = "calyx-libm-hir-passes"
version.workspace = true
edition.workspace = true

[dependencies]
itertools.workspace = true

calyx-libm-hir.workspace = true
calyx-libm-utils.workspace = true
